import wx

program_name = 'CogSlots'
introfile = 'introtext.html'

# slot machine images
SLOT_SIZE = (16,16)
IM_CHERRIES = wx.ART_MISSING_IMAGE
IM_BELL = wx.ART_MISSING_IMAGE
IM_BAR = wx.ART_MISSING_IMAGE
IM_GOLDBARS = wx.ART_MISSING_IMAGE
IM_TREASURECHEST = wx.ART_MISSING_IMAGE

# interface button images
IM_BACKGROUND = wx.ART_MISSING_IMAGE
IM_ORNAMENT_LEFT = wx.ART_MISSING_IMAGE
IM_ORNAMENT_RIGHT = wx.ART_MISSING_IMAGE
IM_DECREASEWAGER = wx.ART_MISSING_IMAGE
IM_DECREASEWAGER_DOWN = wx.ART_MISSING_IMAGE
IM_SPIN = wx.ART_MISSING_IMAGE
IM_SPIN_DOWN = wx.ART_MISSING_IMAGE
IM_INCREASEWAGER = wx.ART_MISSING_IMAGE
IM_INCREASEWAGER_DOWN = wx.ART_MISSING_IMAGE
